#! /bin/bash

[ -z $1 ] && exit 1

for f in $(find $1 -type f -name "*.md"); do
  head -n 1 $f | grep "Table of Contents" -q 
  if [ $? -ne 0 ]; then
    echo "  Generate TOC in progress for $f"
    generate_toc_rb $f > tempfile
    grep -q "#" tempfile
    if [ $? -eq 0 ]; then
      mv $f ${f}_temp 
      cat tempfile ${f}_temp > $f 
      rm ${f}_temp tempfile
    else
  	  echo "     Nothing to TOC"
    fi
  else
  	echo "  TOC already exists for $f"
  fi
done